CREATE DATABASE IF NOT EXISTS clcms;

CREATE TABLE IF NOT EXISTS departments (
    id INTEGER UNSIGNED AUTO_INCREMENT,
    name VARCHAR(30),
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS roles (
    id INTEGER UNSIGNED AUTO_INCREMENT,
    title VARCHAR(50),
    salary DECIMAL UNSIGNED,
    department_id INTEGER UNSIGNED,
    PRIMARY KEY(id),
    FOREIGN KEY(department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS employees (
    id INTEGER UNSIGNED AUTO_INCREMENT,
    first_name VARCHAR(30),
    last_name VARCHAR(30),
    role_id INTEGER UNSIGNED,
    manager_id INTEGER UNSIGNED,
    PRIMARY KEY(id),
    FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE SET NULL,
    FOREIGN KEY(manager_id) REFERENCES employees(id) ON DELETE SET NULL
);